import type { Anchor, Drawing, Inspection, Report } from "./types";

export const SEED_ANCHORS: Anchor[] = [
  {
    id: "RA-03",
    label: "RA-03 · North parapet",
    building: "Kamloops Office Tower",
    location: "Roof level B · NFC-RA-03-BC",
    drawing: "B-1 North parapet detail",
    status: "pass",
    lastTested: "2026-01-12",
    nextDue: "2027-01-12",
    inspector: "Justin Kamata",
    proofResult: "22 kN proof-load passed",
    nfcTag: "NFC-RA-03-BC",
    qrCode: "RA-03",
    position: { x: 554, y: 286 },
  },
  {
    id: "RA-17",
    label: "RA-17 · East ladder line",
    building: "North Ridge Apartments",
    location: "East access · QR + NFC",
    drawing: "R-2 East plan",
    status: "due",
    lastTested: "2025-05-01",
    nextDue: "2026-05-01",
    inspector: "A. Singh",
    proofResult: "22 kN proof-load passed",
    nfcTag: "NFC-RA-17-NRA",
    qrCode: "RA-17",
    position: { x: 232, y: 296 },
  },
  {
    id: "RA-22",
    label: "RA-22 · HVAC curb",
    building: "Civic Plaza",
    location: "Roof zone C · NFC tag",
    drawing: "RF-A",
    status: "pass",
    lastTested: "2025-11-04",
    nextDue: "2026-11-04",
    inspector: "L. Foster",
    proofResult: "22 kN proof-load passed",
    nfcTag: "NFC-RA-22-CP",
    qrCode: "RA-22",
    position: { x: 392, y: 150 },
  },
  {
    id: "RA-08",
    label: "RA-08 · West parapet",
    building: "Kamloops Office Tower",
    location: "Roof level B · West edge",
    drawing: "B-1 West parapet detail",
    status: "failed",
    lastTested: "2026-02-19",
    nextDue: "2026-04-19",
    inspector: "M. Reed",
    proofResult: "Failed at 18 kN — replaced fastener",
    nfcTag: "NFC-RA-08-BC",
    qrCode: "RA-08",
    position: { x: 132, y: 122 },
  },
  {
    id: "RA-11",
    label: "RA-11 · South ladder",
    building: "North Ridge Apartments",
    location: "South stair head",
    drawing: "R-2 South plan",
    status: "pass",
    lastTested: "2026-03-02",
    nextDue: "2027-03-02",
    inspector: "S. Chen",
    proofResult: "22 kN proof-load passed",
    nfcTag: "NFC-RA-11-NRA",
    qrCode: "RA-11",
    position: { x: 612, y: 188 },
  },
];

export const SEED_INSPECTIONS: Inspection[] = [
  {
    id: "ins-seed-1",
    anchorId: "RA-03",
    inspector: "Justin Kamata",
    testDate: "2026-01-12",
    nextDueDate: "2027-01-12",
    result: "pass",
    proofLoad: "22 kN proof-load passed",
    drawingRef: "B-1 North parapet detail",
    notes:
      "Flashing intact, post secure, identification plate readable, NFC verified.",
    photos: [],
    signature: null,
    createdAt: "2026-01-12T15:30:00.000Z",
  },
  {
    id: "ins-seed-2",
    anchorId: "RA-03",
    inspector: "A. Singh",
    testDate: "2025-01-10",
    nextDueDate: "2026-01-10",
    result: "pass",
    proofLoad: "22 kN proof-load passed",
    drawingRef: "B-1 North parapet detail",
    notes: "Re-labeled on roof plan",
    photos: [],
    signature: null,
    createdAt: "2025-01-10T11:12:00.000Z",
  },
  {
    id: "ins-seed-3",
    anchorId: "RA-08",
    inspector: "M. Reed",
    testDate: "2026-02-19",
    nextDueDate: "2026-04-19",
    result: "failed",
    proofLoad: "Failed at 18 kN — replaced fastener",
    drawingRef: "B-1 West parapet detail",
    notes:
      "Fastener pulled before reaching 22 kN. Replaced with chemical anchor; awaiting re-test.",
    photos: [],
    signature: null,
    createdAt: "2026-02-19T18:02:00.000Z",
  },
];

export const SEED_DRAWINGS: Drawing[] = [
  {
    id: "B-1",
    building: "Kamloops Office Tower",
    level: "Roof level B",
    reference: "B-1",
    anchors: [
      { id: "RA-01", x: 232, y: 296, status: "pass" },
      { id: "RA-02", x: 392, y: 150, status: "pass" },
      { id: "RA-03", x: 554, y: 286, status: "pass" },
      { id: "RA-08", x: 132, y: 122, status: "failed" },
    ],
  },
  {
    id: "R-2",
    building: "North Ridge Apartments",
    level: "East roof",
    reference: "R-2",
    anchors: [
      { id: "RA-17", x: 232, y: 296, status: "due" },
      { id: "RA-11", x: 612, y: 188, status: "pass" },
    ],
  },
];

export const SEED_REPORTS: Report[] = [
  {
    id: "rep-1",
    title: "Kamloops Office Tower annual certification",
    description: "12 anchors · signatures included · photos attached",
    building: "Kamloops Office Tower",
    status: "ready",
  },
  {
    id: "rep-2",
    title: "North Ridge Apartments due list",
    description: "6 anchors due in Q2 · grouped by roof zone",
    building: "North Ridge Apartments",
    status: "draft",
  },
  {
    id: "rep-3",
    title: "Inspection log export",
    description:
      "CSV and filtered audit history by building, inspector, or date range",
    building: "All buildings",
    status: "scheduled",
  },
];

export const INSPECTORS = [
  "Justin Kamata",
  "A. Singh",
  "L. Foster",
  "M. Reed",
  "S. Chen",
];
